server:
  port: 6020
spring:
  application:
    name: fire-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:6030
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fire-oauth
          uri: lb://fire-oauth
          predicates:
            - Path=/oauth/**

        - id: fire-user-consumer
          uri: lb://fire-user-consumer
          predicates:
            - Path=/user/**

#            filters: 暂不处理fallback
#              - name: Hystrix
#                order: -1
#                args:
#                  name: failback
#                  fallbackUri: forward:/failbackcontroller