server:
  port: 6020
spring:
  application:
    name: fire-gateway
    cloud:
      gateway:
        routes:
          - id: fire-oauth
            uri: lb://fire-oauth
            predicates:
              - Path=/oauth/**
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:6030

#            filters: 暂不处理fallback
#              - name: Hystrix
#                order: -1
#                args:
#                  name: failback
#                  fallbackUri: forward:/failbackcontroller