---
- hosts: fire-gateway
  remote_user: root
  vars:
    PROJECT_NAME: fire-gateway
    PROJECT_PORT: 6020
  gather_facts: no
  tasks:
    - name: acquire file name
      local_action: shell ls /var/lib/jenkins/workspace/{{PROJECT_NAME}}/{{PROJECT_NAME}}/target/*.jar
      register: file_name
      tags: get_filename

    - name : upload archives
      copy: src={{file_name.stdout}}  dest=/usr/local/fire-cloud/{{PROJECT_NAME}}/{{PROJECT_NAME}}-{{PROJECT_PORT}}.jar
      when: file_name.stdout != ''

    - name: acquire process pid
      tags:
        - test
      shell: "ps -ef | grep -v grep | grep {{PROJECT_NAME}} | awk '{print $2}'"
      register: running_processes

    - name: stop current process
      shell: "kill {{item}}"
      tags:
        - test1
      with_items: "{{running_processes.stdout_lines}}"

    - name: wait for process status
      wait_for:
        path: "/proc/{{item}}/status"
        state: absent
        timeout: 60
      tags:
        - test
      with_items: "{{running_processes.stdout_lines}}"
      ignore_errors: yes
      register: killed_processes

    - name: kill process
      shell: "kill -9 {{ item }}"
      with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

    - name: start new process
      shell: "nohup java -jar /usr/local/fire-cloud/{{PROJECT_NAME}}/{{PROJECT_NAME}}-{{PROJECT_PORT}}.jar &"
      tags: start app


    - name: Wait for {{ PROJECT_PORT }} available
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ PROJECT_PORT }}"
        delay: 5
        timeout: 30
      when: PROJECT_PORT is defined