---
- hosts: fire-gateway
  remote_user: root
  vars:
    PROJECT_NAME: fire-gateway
  tasks:
    - name : 上传Jenkins制品到远程机器
      copy:
        src: "/var/lib/jenkins/workspace/{{PROJECT_NAME}}/{{PROJECT_NAME}}/target/*.jar"
        dest: "/usr/local/fire-cloud/{{PROJECT_NAME}}/"

    - name: 获取上次jar运行的pid
      tags:
        - test
      shell: "ps -ef | grep -v grep | grep {{PROJECT_NAME}} | awk '{print $2}'"
      register: running_processes

    - name: 停止运行进程
      shell: "kill {{item}}"
      tags:
        - test1
      with_items: "{{running_processes.stdout_lines}}"