server:
  port: 9100
spring:
  application:
    name: fire-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:6030
        group: fire-cloud-1
logging:
  config: classpath:log4j2-config.xml