logging:
  config: classpath:log4j2-config.xml
server:
  port: 6010
spring:
  application:
    name: fire-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:6030
        group: fire-base